package app.core.components.cars;

import org.springframework.stereotype.Component;

@Component
public class Car {

}
//AAAUUUTTTOOOWWWIIIRRREEEDDD
//AAAUUUTTTOOOWWWIIIRRREEEDDD
//AAAUUUTTTOOOWWWIIIRRREEEDDD
//AAAUUUTTTOOOWWWIIIRRREEEDDD
//AAAUUUTTTOOOWWWIIIRRREEEDDD
//AAAUUUTTTOOOWWWIIIRRREEEDDD
//AAAUUUTTTOOOWWWIIIRRREEEDDD
//AAAUUUTTTOOOWWWIIIRRREEEDDD
//AAAUUUTTTOOOWWWIIIRRREEEDDD